version: '3.8'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_USER: javaee
      POSTGRES_PASSWORD: javaee
      POSTGRES_DB: sandbox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_main_default

volumes:
  postgres_data:
    driver: local

networks:
  main_main_default:
    external: true